networks:
  default:
    external: true
    name: cvdp-bridge-dataset-f655bdfe
  licnetwork:
    external: true
    name: licnetwork
services:
  xrun:
    command: pytest /src/process.py -v -s
    env_file: ./src/.env
    image: cvdp-cadence-verif:latest
    networks:
    - licnetwork
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
