networks:
  default:
    external: true
    name: cvdp-bridge-dataset-f655bdfe
  licnetwork:
    external: true
    name: licnetwork
services:
  xrun:
    build: .
    command: pytest /src/test_runner.py -v -s
    env_file: ./src/.env
    networks:
    - licnetwork
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
